name: Push to Docker Registries
on:
  push:
    paths-ignore:
      - README.md

  workflow_dispatch:

env:
  DOCKERHUB_REPOSITORY: unfor19/aws-webui
  APP_VERSION: 0.0.2

jobs:
  build-push:
    name: Docker Build Push
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - DOCKERFILE_PATH: Dockerfile
            DOCKER_WORKDIR: .
    env:
      DOCKERFILE_PATH: ${{ matrix.DOCKERFILE_PATH }}
    steps:
      - uses: actions/checkout@v3
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Build
        uses: docker/build-push-action@v3
        with:
          file: ${{ env.DOCKERFILE_PATH }}
          context: ${{ env.DOCKER_WORKDIR }}
          push: false
          platforms: linux/amd64
          tags: |
            ${{ env.DOCKERHUB_REPOSITORY }}:${{ env.APP_VERSION }}-${{ env.GITHUB_REF_SLUG }}
            ${{ env.DOCKERHUB_REPOSITORY }}:${{ env.APP_VERSION }}-${{ env.GITHUB_SHA_SHORT }}
          load: true # For later to run tests on the built image
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Test
        run: yarn test
      - name: Docker Build amd64 and load
        uses: docker/build-push-action@v3
        with:
          file: ${{ env.DOCKERFILE_PATH }}
          context: ${{ env.DOCKER_WORKDIR }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.DOCKERHUB_REPOSITORY }}:${{ env.APP_VERSION }}-${{ env.GITHUB_REF_SLUG }}
            ${{ env.DOCKERHUB_REPOSITORY }}:${{ env.APP_VERSION }}-${{ env.GITHUB_SHA_SHORT }}
          load: false # Must be false to push linux/arm64 images
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Docker Build arm64 and Push
        if: ${{ env.GITHUB_REF_SLUG == 'master' }}
        uses: docker/build-push-action@v3
        with:
          file: ${{ env.DOCKERFILE_PATH }}
          context: ${{ env.DOCKER_WORKDIR }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.DOCKERHUB_REPOSITORY }}:${{ env.APP_VERSION }}-latest
            ${{ env.DOCKERHUB_REPOSITORY }}:latest
          load: false # Must be false to push linux/arm64 images
          cache-from: type=gha
          cache-to: type=gha,mode=max
